"""add_analysis_time_to_user

Revision ID: abb37d307cc5
Revises: e16f5bf6a8aa
Create Date: 2026-01-25 18:46:25.457949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb37d307cc5'
down_revision: Union[str, None] = 'e16f5bf6a8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('analysis_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'analysis_time')
    # ### end Alembic commands ###
