"""add goal_activity_links table

Revision ID: e16f5bf6a8aa
Revises: cf60c00cb3e9
Create Date: 2026-01-21 00:50:06.378272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16f5bf6a8aa'
down_revision: Union[str, None] = 'cf60c00cb3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_activity_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('match_reason', sa.String(), nullable=False),
    sa.Column('contribution_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['extracted_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_activity_links_goal_id'), 'goal_activity_links', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_activity_links_metric_id'), 'goal_activity_links', ['metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_activity_links_metric_id'), table_name='goal_activity_links')
    op.drop_index(op.f('ix_goal_activity_links_goal_id'), table_name='goal_activity_links')
    op.drop_table('goal_activity_links')
    # ### end Alembic commands ###
